{% set version = '1.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stringi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stringi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stringi/stringi_{{ version }}.tar.gz
  sha256: 32df663bb6e9527e1ac265eec2116d26f7b7e62ea5ae7cc5de217cbb8defc362

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('stringi')"           # [not win]
    - "\"%R%\" -e \"library('stringi')\""  # [win]

about:
  home: http://www.gagolewski.com/software/stringi/ http://site.icu-project.org/ http://www.unicode.org/
  license: FOSS
  license_file: LICENSE
  summary: 'Allows for fast, correct, consistent, portable, as well as convenient character string/text
    processing in every locale and any native encoding. Owing to the use of the ''ICU''
    library, the package provides ''R'' users with platform-independent functions known
    to ''Java'', ''Perl'', ''Python'', ''PHP'', and ''Ruby'' programmers. Available
    features include: pattern searching (e.g., with ''Java''-like regular expressions
    or the ''Unicode'' collation algorithm), random string generation, case mapping,
    string transliteration, concatenation, Unicode normalization, date-time formatting
    and parsing, and many more.'
  license_family: OTHER

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
    - mariusvniekerk
    - philip-khor

# Package: stringi
# Version: 1.3.1
# Date: 2019-02-10
# Title: Character String Processing Facilities
# Description: Fast, correct, consistent, portable, as well as convenient character string/text processing in every locale and any native encoding. Owing to the use of the 'ICU' (International Components for Unicode) library, the package provides 'R' users with platform-independent functions known to 'Java', 'Perl', 'Python', 'PHP', and 'Ruby' programmers. Available features include: pattern searching (e.g., with 'Java'-like regular expressions or the 'Unicode' collation algorithm), random string generation, case mapping, string transliteration, concatenation, Unicode normalization, date-time formatting and parsing, and many more.
# URL: http://www.gagolewski.com/software/stringi/ http://site.icu-project.org/ http://www.unicode.org/
# BugReports: http://github.com/gagolews/stringi/issues
# SystemRequirements: ICU4C (>= 52, optional)
# Type: Package
# Depends: R (>= 2.14)
# Imports: tools, utils, stats
# Biarch: TRUE
# License: file LICENSE
# Author: Marek Gagolewski [aut, cre], Bartek Tartanus [ctb], and other contributors (stringi source code); IBM, Unicode, Inc., and other contributors (ICU4C source code); Unicode, Inc. (Unicode Character Database)
# Maintainer: Marek Gagolewski <marek@gagolewski.com>
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-02-10 12:40:21 UTC; gagolews
# License_is_FOSS: yes
# Repository: CRAN
# Date/Publication: 2019-02-13 17:40:03 UTC
