appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: gQGh/HHK2nAE6hQIzdHhjyaJiIh0+neNPRlapQ91Ca6F2gP8z8fq82GZm7NkbgYEobLL9sed1ThOjoSk11S19xcFS30FEzbAQe9X+5xDyqJX51+gYdux4z5pUE9Ob5h8pKP7kJkaqKlo+Q/11N5seOLtG0gPe69t2Go+VJC/RZEsG0ZTwLJ++FTrYilSM0ISoCHkrzgNGcUXgn+d8hDTz8cydNVIzG4eDSebDHQOP2waFCiHOtn8FKGO3wZS8rNecCcll9ydONkmBP4R6JsyRghxFLIkYLAoOuWVnhD4XXrKiPSRevqpoBukdEhNOCC3Zvkhe0FBOhtSlDzKNWmnn4CUpC2/hST4LN8pkPI893Zl0YpbElaMuG5qeANU1vBiJ+iKk3QocJS4h7kKJRwGHk2VX6sprH9n/5c5jqaSjDZCfWogCXEZLYxe32kWKCLiHACWVgv8wIU0GZuwoSZup9RUJ5GdsTK9A9CYfaQBZGq4aBZ7ntPvlh8xE/eOKOI4Q4lVgIFZDr5p2XNbl7oDQ3qwR7hF8DBDFfjY0EtomTkIeVOB3FM2Vr1rXI3x/eaq0DbSl86U4cqQEcrGZrAdXZwnZHWKyTYB5iArylG2geo5XT6gVkb4MKlxsMg98ZjdN9+dmCsMZ+KXr6KwbBd0BjiUZRAQIMsWBIDucbrVl6c=}
bot:
  automerge: true
conda_forge_output_validation: false
